### ISSUE TITLE
Support for arm64 (M1)

### ISSUE THREAD

**Issue by PiotrZakrzewski** [Kuifje02/vrpy#133]
hi! Thanks for open sourcing your work!
I am not sure if you are were, VRPy does not seem to work on M1.

when I attempt 
```
from vrpy import VehicleRoutingProblem
```
On MacOs Monetrey with M1 processor I get
```
Traceback (most recent call last):
  File "/Users/piotrzakrzewski/code/vrp/main.py", line 2, in <module>
    from vrpy import VehicleRoutingProblem
  File "/Users/piotrzakrzewski/code/vrp/.env/lib/python3.10/site-packages/vrpy/__init__.py", line 2, in <module>
    from vrpy.vrp import VehicleRoutingProblem
  File "/Users/piotrzakrzewski/code/vrp/.env/lib/python3.10/site-packages/vrpy/vrp.py", line 8, in <module>
    from vrpy.subproblem_cspy import _SubProblemCSPY
  File "/Users/piotrzakrzewski/code/vrp/.env/lib/python3.10/site-packages/vrpy/subproblem_cspy.py", line 5, in <module>
    from cspy import BiDirectional, REFCallback
  File "/Users/piotrzakrzewski/code/vrp/.env/lib/python3.10/site-packages/cspy/__init__.py", line 1, in <module>
    from cspy.algorithms.bidirectional import BiDirectional, REFCallback
  File "/Users/piotrzakrzewski/code/vrp/.env/lib/python3.10/site-packages/cspy/algorithms/bidirectional.py", line 9, in <module>
    from .pyBiDirectionalCpp import BiDirectionalCpp, REFCallback, DoubleVector
  File "/Users/piotrzakrzewski/code/vrp/.env/lib/python3.10/site-packages/cspy/algorithms/pyBiDirectionalCpp.py", line 13, in <module>
    from . import _pyBiDirectionalCpp
ImportError: dlopen(/Users/piotrzakrzewski/code/vrp/.env/lib/python3.10/site-packages/cspy/algorithms/_pyBiDirectionalCpp.so, 0x0002): tried: '/Users/piotrzakrzewski/code/vrp/.env/lib/python3.10/site-packages/cspy/algorithms/_pyBiDirectionalCpp.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
```

Seems to be caused by `cspy`?

**Comment by torressa** [comment]
Just uploaded a wheel for Python 3.10.
Sorry, there is an issue with the build actions (it is mentioned [here](https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/))
