### ISSUE TITLE
P-n23-k8.vrp data set does not run (cspy)

### ISSUE THREAD

**Issue by Kuifje02** [Kuifje02/vrpy#18]
For some reason the data set `P-n23-k8.vrp` from Augerat does not run with cspy, I cannot figure out why for the moment (all other data sets are ok, for some reason this one does not). It is in the data [folder](https://github.com/Kuifje02/vrpy/tree/dev/examples/benchmarks/data).

```
P-n23-k8 cspy
=========
vrpy.main - INFO - new upper bound : max num stops = 8
vrpy.main - INFO - iteration 0, 1098.4
Traceback (most recent call last):
  File "cvrp_augerat.py", line 219, in <module>
    data.solve(cspy=cspy, exact=True, time_limit=60)
  File "cvrp_augerat.py", line 145, in solve
    prob.solve(cspy=cspy, exact=exact, time_limit=time_limit)
  File "../..\vrpy\main.py", line 149, in solve
    self.routes, more_routes = subproblem.solve(time_limit)
  File "../..\vrpy\subproblem_cspy.py", line 103, in solve
    logger.debug("cost = %s" % self.alg.total_cost)
  File "../../../cspy\cspy\algorithms\bidirectional.py", line 176, in total_cost
    raise Exception("Please call the .run() method first")
Exception: Please call the .run() method first
```

**Comment by torressa** [comment]
I think the problem is with the new beta heuristic. It works when I comment it out, and when I don't, I get this error:

```none
  File "../../vrpy/main.py", line 194, in solve
    self.best_value, self.best_routes_as_graphs = masterproblem_mip.solve()
  File "../../vrpy/master_solve_pulp.py", line 42, in solve
    shortest_path(r, "Source", "Sink"),
  File "/home/torressa/.local/lib/python3.8/site-packages/networkx/algorithms/shortest_paths/generic.py", line 170, in shortest_path
    paths = nx.bidirectional_shortest_path(G, source, target)
  File "/home/torressa/.local/lib/python3.8/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 226, in bidirectional_shortest_path
    results = _bidirectional_pred_succ(G, source, target)
  File "/home/torressa/.local/lib/python3.8/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 294, in _bidirectional_pred_succ
    raise nx.NetworkXNoPath("No path between %s and %s." % (source, target))
networkx.exception.NetworkXNoPath: No path between Source and Sink.

```

**Comment by anjn98** [comment]
Hi i am getting the error below while trying to run the vrpy module, seems similar to the issue above, can you please help 

`INFO:vrpy.vrp:new upper bound : max num stops = 6
INFO:vrpy.vrp:iteration 0, 200004
INFO:vrpy.vrp:iteration 1, 38402.
INFO:vrpy.vrp:iteration 2, 38402.
INFO:vrpy.vrp:iteration 3, 38402.
INFO:vrpy.vrp:iteration 4, 31528.
INFO:vrpy.vrp:iteration 5, 26827.
INFO:vrpy.vrp:iteration 6, 13563.
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    solver(deliveryArray, vehicleFleet, depotDetails)
  File "main.py", line 101, in solver
    finalSolution.solve()
  File "/home/anjan/vrpy/venv/lib/python3.8/site-packages/vrpy/vrp.py", line 238, in solve
    self._solve(dive, solver)
  File "/home/anjan/vrpy/venv/lib/python3.8/site-packages/vrpy/vrp.py", line 454, in _solve
    self._column_generation()
  File "/home/anjan/vrpy/venv/lib/python3.8/site-packages/vrpy/vrp.py", line 476, in _column_generation
    self._find_columns()
  File "/home/anjan/vrpy/venv/lib/python3.8/site-packages/vrpy/vrp.py", line 518, in _find_columns
    self._more_routes = self._solve_subproblem_with_heuristic(
  File "/home/anjan/vrpy/venv/lib/python3.8/site-packages/vrpy/vrp.py", line 583, in _solve_subproblem_with_heuristic
    more_columns = self._attempt_solve_best_edges1(vehicle=vehicle,
  File "/home/anjan/vrpy/venv/lib/python3.8/site-packages/vrpy/vrp.py", line 625, in _attempt_solve_best_edges1
    self.routes, self._more_routes = subproblem.solve(
  File "/home/anjan/vrpy/venv/lib/python3.8/site-packages/vrpy/subproblem_cspy.py", line 108, in solve
    logger.debug("cost = %s" % alg.total_cost)
  File "/home/anjan/vrpy/venv/lib/python3.8/site-packages/cspy/algorithms/bidirectional.py", line 163, in total_cost
    raise Exception("Please call the .run() method first")
Exception: Please call the .run() method first`

**Comment by torressa** [comment]
Hey @anjn98 
Hmm seems to work for some iterations.. Can you try setting `pricing_strategy="Exact"` in the `.solve` call (see [docs](https://vrpy.readthedocs.io/en/latest/api.html#vrpy.vrp.VehicleRoutingProblem.solve))

**Comment by anjn98** [comment]
Its working now after adding the parameter. Thank you so much @torressa for your help

**Comment by torressa** [comment]
Cool!
It will be significantly slower on large instances though, so maybe try playing around with the values
